extends:
  - spectral:oas

rules:
  operation-description:
    description: "Operations must have descriptions."
    given: "$.paths[*][*]"
    severity: warn
    then:
      field: description
      function: truthy

  operation-summary:
    description: "Operations must have summaries."
    given: "$.paths[*][*]"
    severity: warn
    then:
      field: summary
      function: truthy